apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  labels:
    app: myapp
    costcenter: amer
    location: GT
    type: frontend

spec:
  containers:
    - name: nginx-container
      image: nginx
